MODEL:
  NAME: "V39"
  META_ARCHITECTURE: "CenterMaskGNN"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  GNN:
    NAME: "TransitionGNN"
  FCOS:
    NUM_CLASSES: 80
  MASK_ON: True
  MASKIOU_ON: True
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
    NUM_CLASSES: 80
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  SEM_SEG_HEAD:
    NUM_CLASSES : 80
  RETINANET:
    NUM_CLASSES : 80

SOLVER:
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 24
  BASE_LR: 0.005  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 70000)
  MAX_ITER: 75000
  WARMUP_ITERS: 0

TEST:
  EVAL_PERIOD: 200
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #RANDOM_FLIP: none

DEBUG:
  RETURN_GT: False
